import_params:
  import_file_path: 'C:\Users\1699\tmp\datasets\C61_balanced_split\C61_Airline_balanced_split\model (copy)\test_scores.csv'
  image_name_column: 'img'
  score_column: 'scores'
  truth_column: 'truth'
  extract_info_from_file_name: true
  regex_expression_folder_path: '([^\\]+)$'
  regex_expression_file_name: '(\d+)_(\d+)_(\d+).\w+$'
  category_map: 
    'Airline': 1
    'Verformt': 1
    'BeschStopfen_': 1
    'MarkStopfen_': 1
    'PartikelIglo_': 1
    'FaserStopfen': 1
    'LyoStopfen': 1_
    'Gut': 0

export_params:
  export_path: 'C:\Users\1699\tmp\datasets\C61_balanced_split\C61_Airline_balanced_split\model (copy)'

evaluation parameters:
  prediction_class_to_value_map:
    'good': 0
    'bad': 1
  prediction_classes:
    - 'good'
    - 'bad'