import_params:
  import_file_path: 'C:\Users\1699\Repositories\ai_results_viz\ai_pipeline_export\data\test_scores.csv'
  image_name_column: 'img'
  score_column: 'scores'
  truth_column: 'truth'
  extract_info_from_file_name: true
  regex_expression_file_name: '^(.+?)_.+_(\d+)_(\d+)_(\d+)'
  category_map: 
    'BeschSW': 1 
    'KratzerSW': 1
    'Airline': 1
    'Gut' : 0

export_params:
  export_path: 'C:\Users\1699\Repositories\ai_results_viz\ai_pipeline_export\data'