import_params:
  import_file_path: 'C:\Users\1699\Repositories\ai_results_viz\ai_pipeline_export\data\test_scores.csv'
  prediction_categories: ['good', 'bad']
  prediction_categories_to_index: {'good': 0, 'bad': 1}
  positive_class: 'good'
  negative_classes: ['bad']
  extract_info_from_file_name: true
  regex_expression_file_name: '^(.+?)_.+_(\d+)_(\d+)_(\d+)'
  threshold: 0.5
  category_map: 
    'BeschStopfen': 1 
    'FaserStopfen': 1
    'Good': 0
    'LyoStopfen': 1
    'MarkStopfen': 1
    'PartikelIglo': 1

export_params:
  export_path: 'C:\Users\1699\Repositories\ai_results_viz\ai_pipeline_export\data'