import_params:
  import_file_path: 'Z:\ejectx_repositories\results\c82_binary\model_20221208_3cp50_37_edge_length\test_scores\export\image_based_scores.csv'
  category_to_model_class_map:
    "airline_sw": "bad"
    "damage_sw": "bad"
    "good": "good"
    "lyophilisate_plug": "good"
    "scratch_sw": "bad"
  positive_class: 'good'
  pos_label: 1
  extract_info_from_file_name: true
  regex_expression_file_name: '^(.+?)_[(good)|(bad)].+_(\d+)_(\d+)_(\d+)'
  benchmark: [8.6, 4.7]

export_params:
  export_path: 'Z:\ejectx_repositories\results\c82_binary\model_20221208_3cp50_37_edge_length\test_scores\export\'